# Generated by Django 4.2.6 on 2023-10-04 19:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EventSavvy', '0005_alter_eventrecord_organiser_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganiserRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image_url', models.CharField(max_length=255)),
                ('rating', models.DecimalField(decimal_places=1, max_digits=3)),
                ('tagline', models.CharField(max_length=255)),
                ('organiser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EventSavvy.organiser')),
            ],
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField()),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EventSavvy.eventrecord')),
            ],
        ),
    ]
