# Generated by Django 4.2.6 on 2023-10-04 19:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EventSavvy', '0006_organiserrecord_expense'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='organiser',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='EventSavvy.organiser'),
        ),
    ]
